# Generated by Django 2.2.2 on 2019-08-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signmenu', '0002_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='123456', max_length=30),
        ),
    ]
