# Generated by Django 2.2.2 on 2019-08-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signmenu', '0003_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
